---
language: python
python:
  - "3.7-dev"

sudo: required

services:
  - docker

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install tox

script:
  - tox

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t clayman74/passport .
    fi

notifications:
  slack: claymanpro:5w9rLMZvWaCzlzUJPrUChXY5
