---
language: python
python:
  - "3.6"

sudo: required

services:
  - docker

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install tox

script:
  - tox

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    make build-image;
    make publish-image;
    fi

notifications:
  slack: claymanpro:5w9rLMZvWaCzlzUJPrUChXY5
