---

# Build application package

- name: Set facts
  set_fact:
    app_root: "{{ inventory_dir }}"
    app_dist: "{{ inventory_dir }}/dist"

- name: Cleanup distribution folder
  file: state="absent" path="{{ app_dist }}/"

- name: Create distribution
  shell: python setup.py sdist chdir="{{ app_root }}"

- name: Get distribution version
  shell: python setup.py --version chdir="{{ app_root }}"
  register: output

- name: Set current package version
  set_fact:
    app_version: "{{ output.stdout }}"
    app_image: "{{ app_maintainer }}/{{ app_name }}:{{ output.stdout }}"

- name: Create Dockerfile
  template: src=Dockerfile.j2 dest="{{ app_dist }}/Dockerfile"

- name: Build app image
  docker_image:
    name: "{{ app_image }}"
    path: "{{ app_dist }}"

- name: Login in Docker Hub
  docker_login:
    username: "{{ lookup('env', 'DOCKER_USER') }}"
    password: "{{ lookup('env', 'DOCKER_PASS') }}"
    email: "{{ lookup('env', 'DOCKER_EMAIL') }}"
  when: lookup('env', 'DOCKER_USER') and lookup('env', 'DOCKER_PASS') and lookup('env', 'DOCKER_EMAIL')

- name: Push image to Docker Hub
  shell: "docker push {{ app_image }}"
  when: lookup('env', 'DOCKER_USER') and lookup('env', 'DOCKER_PASS') and lookup('env', 'DOCKER_EMAIL')
