---

# Prepare app config

- name: Create app folders
  file: path={{ item }} state=directory
  with_items:
    - "/etc/service/{{ app_name }}_consul_template"
    - "/opt/projects/{{ app_name }}"

- name: Assemble app config
  template: src="config.yml.j2" dest="/opt/projects/{{ app_name }}/config.yml"

- include: database.yml

- name: Assemble consul-template config
  template:
    src: nginx.consul-template.conf.j2
    dest: "/etc/consul-templates/{{ app_name }}.conf"

- name: Assemble consul-template service file
  template:
    src: consul-template.service.j2
    dest: "/etc/service/{{ app_name }}_consul_template/run"
    mode: "a+x"
