---

- hosts: localhost
  tasks:
    - name: Prepare folder for credentials
      file:
        path: "{{ inventory_dir }}/.credentials/{{ item }}/users/{{ hostvars[item]['ansible_user'] }}/"
        state: directory
        mode: 0755
      with_items: "{{ groups['servers'] }}"

    - name: Download private keys for servers
      hashivault_read:
        mount_point: "credentials"
        secret: "clusters/cloud/nodes/{{ item }}/users/{{ hostvars[item]['ansible_user'] }}"
        key: 'private_key'
        version: 2
      with_items: "{{ groups['servers'] }}"
      loop_control:
        label: "{{ item }}"
      register: 'private_keys'

    - name: Write private key to file
      copy:
        content: "{{ item.value }}"
        dest: "{{ inventory_dir }}/.credentials/{{ item.item }}/users/{{ hostvars[item.item]['ansible_user'] }}/id_rsa"
        mode: 0600
      with_items: "{{ private_keys.results }}"
      loop_control:
        label: "{{ item.item }}"


- hosts: servers
  become: true

  vars:
    app: passport

    namespace: micro
    serviceAccount: micro

    image: ghcr.io/clayman-micro/passport
    version: "{{ lookup('env','PASSPORT_VERSION')|default('latest') }}"

    replicas: 1

  tasks:
    - name: Prepare folder for charts
      file:
        path: /opt/micro
        state: directory
        mode: 0755

    - name: Get Helm charts
      ansible.builtin.git:
        repo: "https://github.com/clayman-micro/helm-chart.git"
        version: v1.1.0
        dest: /opt/micro/helm-chart

    - name: Deploy Helm chart
      community.kubernetes.helm:
        name: "{{ app }}"
        chart_ref: /opt/micro/helm-chart/charts/micro
        release_namespace: "{{ namespace }}"
        values:
          image:
            repository: "{{ image }}"
            tag: "{{ version }}"

          replicas: "{{ replicas }}"

          serviceAccount:
            name: "{{ serviceAccount  }}"

          imagePullSecrets:
            - name: ghcr

          migrations:
            enabled: true

          env:
            - name: POSTGRES_HOST
              value: 10.0.0.1
            - name: VAULT_ADDR
              value: https://vault.clayman.pro
            - name: VAULT_AUTH_METHOD
              value: kubernetes
            - name: VAULT_SERVICE_NAME
              value: micro

          livenessProbe:
            enabled: true

          readinessProbe:
            enabled: true
