---

- hosts: locals
  roles:
    - role: clayman74.digitalocean-provision
      digitalocean_provision_token: "{{ lookup('env', 'DO_TOKEN') }}"
      digitalocean_provision_inventory_group: "{{ groups['cloud'] }}"
      digitalocean_provision_ssh_key: "{{ inventory_hostname }}"

- hosts: cloud
  vars:
    network: backend

    loadbalancer_owner_email: sumorokov.k@gmail.com
    loadbalancer_domains: ['clayman.pro', 'passport.clayman.pro']

    app_network: passport_network

  pre_tasks:
    - name: Set credentials path
      set_fact:
        credentials_path: "{{ lookup('env','HOME') }}/.credentials/'{{ inventory_hostname }}"

    - name: Generate required passwords
      set_fact:
        postgresql_password: "{{ lookup('password', '{{ credentials_path }}/postgresql/password length=20') }}"

  roles:
    - role: clayman74.consul
      consul_image: consul
      consul_container_name: consul
      consul_network: "{{ network }}"

    - role: clayman74.loadbalancer
      loadbalancer_image: clayman74/loadbalancer
      loadbalancer_container_name: loadbalancer
      loadbalancer_networks:
        - name: backend

    - role: clayman74.postgresql
      postgresql_network: "{{ network }}"
      postgresql_image: postgres:9.6-alpine
