name: Release and deploy

on:
  create:
    tags:
      - v*

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - uses: actions/setup-python@v1
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Install requirements
        run: pip install poetry tox

      - name: Run tests
        run: tox

      - name: Send notification to Telegram
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT }}
          token: ${{ secrets.TELEGRAM_SECRET }}
          args: ${{ github.repository }} tests for version `${{ steps.vars.outputs.tag }}` - ${{ job.status }}

  publish:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Publish to Docker Repository
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ghcr.io/clayman-micro/passport
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ghcr.io
          tag_names: true

      - name: Send notification to Telegram
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT }}
          token: ${{ secrets.TELEGRAM_SECRET }}
          args: ${{ github.repository }} build image for version `${{ steps.vars.outputs.tag }}` - ${{ job.status }}

  deploy:
    needs: [publish]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - uses: actions/setup-python@v1
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Install requirements
        run: pip install httpie ansible==2.10.1 ansible-modules-hashivault==4.5.6

      - name: Deploy new version
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          PASSPORT_VERSION: ${{ steps.vars.outputs.tag }}
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          VAULT_ROLE_ID: ${{ secrets.VAULT_ROLE_ID }}
          VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}
        run: |
          export VAULT_TOKEN="$(httpie $VAULT_ADDR/v1/auth/approle/login role_id=$VAULT_ROLE_ID secret_id=$VAULT_SECRET_ID | python3 -c "import sys,json; print(json.load(sys.stdin)['auth']['client_token'])")"
          ansible-playbook -i ansible/inventory ansible/deploy.yml

      - name: Send notification to Telegram
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT }}
          token: ${{ secrets.TELEGRAM_SECRET }}
          args: ${{ github.repository }} deploy version `${{ steps.vars.outputs.tag }}` - ${{ job.status }}
